import os
import sys
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from dotenv import load_dotenv

load_dotenv()

def create_pdf_report(summary_text: str, scenario_text: str = None, output_filename: str = None):
    """
    Create a professional PDF report from the stress test summary.
    
    Args:
        summary_text (str): The AI-generated summary
        scenario_text (str): Original scenario text (optional)
        output_filename (str): Output PDF filename (optional)
    
    Returns:
        str: Path to the generated PDF file
    """
    
    # Generate filename if not provided
    if not output_filename:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_filename = f"stress_test_report_{timestamp}.pdf"
    
    # Ensure reports directory exists
    reports_dir = "reports"
    if not os.path.exists(reports_dir):
        os.makedirs(reports_dir)
    
    output_path = os.path.join(reports_dir, output_filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=60,
        leftMargin=60,
        topMargin=60,
        bottomMargin=60
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Custom styles for professional appearance
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Title'],
        fontSize=26,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#1f4e79'),
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontSize=14,
        spaceAfter=25,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#5b9bd5'),
        fontStyle='italic'
    )
    
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=15,
        spaceBefore=25,
        textColor=colors.HexColor('#1f4e79'),
        fontName='Helvetica-Bold',
        borderWidth=0,
        borderColor=colors.HexColor('#1f4e79'),
        borderPadding=5
    )
    
    subsection_style = ParagraphStyle(
        'Subsection',
        parent=styles['Heading2'],
        fontSize=13,
        spaceAfter=12,
        spaceBefore=15,
        textColor=colors.HexColor('#2e5090'),
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=12,
        alignment=TA_JUSTIFY,
        leftIndent=15,
        rightIndent=15,
        leading=14
    )
    
    bullet_style = ParagraphStyle(
        'BulletPoint',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=8,
        leftIndent=30,
        rightIndent=15,
        leading=14,
        bulletIndent=15
    )
    
    # Build story (content)
    story = []
    
    # Title page
    story.append(Paragraph("Financial Stress Test Analysis Report", title_style))
    story.append(Spacer(1, 0.3*inch))
    
    story.append(Paragraph("AI-Powered Regulatory Scenario Assessment", subtitle_style))
    story.append(Spacer(1, 0.4*inch))
    
    # Executive summary box
    exec_summary_data = [
        ["Report Type", "Stress Test Scenario Analysis"],
        ["Analysis Date", datetime.now().strftime("%B %d, %Y")],
        ["AI Engine", "Azure OpenAI (GPT-4o)"],
        ["Framework", "Bank of England Methodology"],
        ["Generated By", "Azure AI Foundry Platform"]
    ]
    
    exec_table = Table(exec_summary_data, colWidths=[2.2*inch, 3.3*inch])
    exec_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4e79')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f2f2f2')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#1f4e79'))
    ]))
    
    story.append(exec_table)
    story.append(PageBreak())
    
    # Original scenario section (if provided)
    if scenario_text:
        story.append(Paragraph("Input Stress Test Scenario", section_heading_style))
        
        # Clean scenario text and format nicely
        scenario_paragraphs = [p.strip() for p in scenario_text.strip().split('\n') if p.strip()]
        for para in scenario_paragraphs:
            story.append(Paragraph(para, body_style))
        
        story.append(Spacer(1, 0.3*inch))
    
    # AI Analysis section
    story.append(Paragraph("Detailed Analysis", section_heading_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Process the summary text intelligently
    lines = [line.strip() for line in summary_text.split('\n') if line.strip()]
    
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # Check if this looks like a section header (title case, no sentence-ending punctuation)
        if (line.isupper() or 
            (line.istitle() and not line.endswith(('.', '!', '?', ':')) and len(line.split()) <= 6) or
            line.endswith(':') and len(line.split()) <= 8):
            # This is likely a section header
            clean_header = line.rstrip(':')
            story.append(Paragraph(clean_header, subsection_style))
        
        # Check if this is a bullet point (starts with -, •, or similar)
        elif line.startswith(('-', '•', '*', '◦')):
            bullet_text = line[1:].strip()
            story.append(Paragraph(f"• {bullet_text}", bullet_style))
        
        # Check if this is a numbered item
        elif any(line.startswith(f"{j}.") for j in range(1, 10)):
            story.append(Paragraph(line, bullet_style))
        
        # Regular paragraph
        else:
            story.append(Paragraph(line, body_style))
        
        i += 1
    
    # Professional footer
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("Report Metadata", section_heading_style))
    
    footer_data = [
        ["Generated", datetime.now().strftime("%B %d, %Y at %I:%M %p")],
        ["Methodology", "Bank of England Stress Testing Framework"],
        ["AI Model", "Azure OpenAI GPT-4o"],
        ["Platform", "Azure AI Foundry"],
        ["Disclaimer", "This analysis is AI-generated and should be reviewed by qualified financial professionals"]
    ]
    
    footer_table = Table(footer_data, colWidths=[1.8*inch, 3.7*inch])
    footer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1f4e79')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6'))
    ]))
    
    story.append(footer_table)
    
    # Build PDF
    doc.build(story)
    
    return output_path

def generate_report_from_agent():
    """
    Run the agent and generate a PDF report from its output.
    """
    try:
        # Import and run the summarize tool
        from tools.summarize_tool.summarize_tool import main as summarize_tool
        
        # Sample scenario
        scenario_input = '''
        In the 2022 Bank of England stress test, the scenario featured a deep global recession with UK GDP falling by 5%, unemployment rising to 8.5%, and property prices dropping by over 30%. The stress also included a sharp rise in interest rates and inflation.
        '''
        
        print("Running stress test analysis...")
        result = summarize_tool(scenario_input.strip())
        
        if result and "summary" in result:
            print("Generating PDF report...")
            pdf_path = create_pdf_report(
                summary_text=result["summary"],
                scenario_text=scenario_input.strip()
            )
            
            print(f"✅ PDF report generated successfully!")
            print(f"📄 Report saved to: {pdf_path}")
            
            return pdf_path
        else:
            print("❌ Error: No summary generated from agent")
            return None
            
    except Exception as e:
        print(f"❌ Error generating report: {e}")
        return None

if __name__ == "__main__":
    # Check if summary text is provided as argument
    if len(sys.argv) > 1:
        summary_text = sys.argv[1]
        pdf_path = create_pdf_report(summary_text)
        print(f"PDF report generated: {pdf_path}")
    else:
        # Run the full pipeline
        generate_report_from_agent()
