"""
Requirements Analyst Agent for Multi-Agent Financial Stress Test Workflow

This agent is responsible for:
- Analyzing user requirements for stress testing
- Validating input parameters and constraints
- Setting up the foundation for subsequent analysis stages
- Providing recommendations for stress test configuration
"""

from typing import Dict, Any, List, Optional, Tuple
import json
import os
from datetime import datetime
from dataclasses import asdict

from ..shared.state_manager import AgentOutput, WorkflowStage, WorkflowState
from ..shared.user_interaction import UserInteraction, ValidationResult


class RequirementsAnalyst:
    """
    Requirements Analyst Agent for Financial Stress Testing.
    
    This agent analyzes user requirements and sets up the foundation
    for the stress test workflow. It validates parameters, identifies
    constraints, and provides configuration recommendations.
    """
    
    def __init__(self, user_interaction: UserInteraction):
        """
        Initialize the Requirements Analyst.
        
        Args:
            user_interaction: UserInteraction instance for CLI handling
        """
        self.agent_name = "Requirements Analyst"
        self.stage = WorkflowStage.REQUIREMENTS_ANALYSIS
        self.ui = user_interaction
        
        # Scenario types that will be dynamically generated by LLM
        self.scenario_types = [
            "market_crash",
            "interest_rate_shock", 
            "credit_crisis",
            "geopolitical_risk",
            "inflation_shock",
            "liquidity_crisis",
            "operational_risk",
            "cyber_security_event",
            "climate_risk",
            "combined_scenario"
        ]
        
        # Supported portfolio types
        self.portfolio_types = {
            "equity_portfolio": "Equity-focused investment portfolio",
            "fixed_income": "Fixed income/bond portfolio",
            "mixed_portfolio": "Mixed asset allocation portfolio",
            "hedge_fund": "Alternative investment/hedge fund portfolio",
            "pension_fund": "Pension fund portfolio",
            "insurance_portfolio": "Insurance company investment portfolio",
            "bank_portfolio": "Banking institution portfolio"
        }
    
    def analyze_requirements(self, workflow_state: WorkflowState) -> AgentOutput:
        """
        Main method to analyze user requirements for stress testing.
        
        Args:
            workflow_state: Current workflow state
            
        Returns:
            AgentOutput with requirements analysis results
        """
        self.ui.display_stage_header(
            self.stage, 
            "Analyzing user requirements and setting up stress test parameters"
        )
        
        try:
            # Collect user requirements
            requirements = self._collect_requirements()
            
            # Validate requirements
            validation_results = self._validate_requirements(requirements)
            
            # Generate LLM-based scenario recommendations
            scenario_recommendations = self._generate_llm_scenario_recommendations(requirements)
            
            # Generate general recommendations
            recommendations = self._generate_recommendations(requirements, validation_results, scenario_recommendations)
            
            # Prepare output data
            output_data = {
                "requirements": requirements,
                "validation_results": validation_results,
                "recommended_scenarios": scenario_recommendations,
                "configuration": self._build_configuration(requirements, recommendations, scenario_recommendations)
            }
            
            # Create agent output
            output = AgentOutput(
                agent_name=self.agent_name,
                stage=self.stage,
                summary=self._create_summary(requirements, validation_results),
                key_findings=self._extract_key_findings(requirements, validation_results),
                recommendations=recommendations,
                data=output_data,
                errors=validation_results.get("errors", []),
                timestamp=datetime.now().isoformat()
            )
            
            # Display results to user
            self.ui.display_agent_output(output)
            
            return output
            
        except Exception as e:
            error_msg = f"Error in requirements analysis: {str(e)}"
            self.ui.display_error(error_msg, self.stage)
            
            return AgentOutput(
                agent_name=self.agent_name,
                stage=self.stage,
                summary="Requirements analysis failed due to error",
                key_findings=[],
                recommendations=["Review input parameters and try again"],
                data={},
                errors=[error_msg],
                timestamp=datetime.now().isoformat()
            )
    
    def _collect_requirements(self) -> Dict[str, Any]:
        """Collect requirements from user input."""
        self.ui.display_info("Collecting stress test requirements...")
        
        requirements = {}
        
        # Portfolio type
        self.ui.display_info("\nAvailable portfolio types:")
        for key, description in self.portfolio_types.items():
            print(f"  {key}: {description}")
        
        portfolio_type = self.ui.get_user_input(
            "Enter portfolio type:",
            validator=lambda x: x in self.portfolio_types,
            error_msg=f"Please choose from: {', '.join(self.portfolio_types.keys())}"
        )
        requirements["portfolio_type"] = portfolio_type
        
        # Portfolio value
        portfolio_value = self.ui.get_user_input(
            "Enter total portfolio value (e.g., 100000000 for $100M):",
            validator=lambda x: x.isdigit() and int(x) > 0,
            error_msg="Please enter a positive number"
        )
        requirements["portfolio_value"] = int(portfolio_value)
        
        # Risk tolerance
        risk_tolerance = self.ui.get_user_input(
            "Enter risk tolerance (conservative/moderate/aggressive):",
            validator=lambda x: x.lower() in ["conservative", "moderate", "aggressive"],
            error_msg="Please enter: conservative, moderate, or aggressive"
        )
        requirements["risk_tolerance"] = risk_tolerance.lower()
        
        # Time horizon
        time_horizon = self.ui.get_user_input(
            "Enter investment time horizon in years (e.g., 5):",
            validator=lambda x: x.isdigit() and 1 <= int(x) <= 50,
            error_msg="Please enter a number between 1 and 50"
        )
        requirements["time_horizon"] = int(time_horizon)
        
        # Regulatory requirements
        has_regulatory = self.ui.confirm_action("Are there specific regulatory requirements (e.g., Basel III, Solvency II)?")
        if has_regulatory:
            regulatory_framework = self.ui.get_user_input("Enter regulatory framework (e.g., basel_iii, solvency_ii, none):")
            requirements["regulatory_framework"] = regulatory_framework
        else:
            requirements["regulatory_framework"] = "none"
        
        # Custom scenarios
        has_custom_scenarios = self.ui.confirm_action("Do you want to define custom stress scenarios?")
        if has_custom_scenarios:
            requirements["custom_scenarios"] = self._collect_custom_scenarios()
        else:
            requirements["custom_scenarios"] = []
        
        # Output preferences
        requirements["output_format"] = self.ui.get_user_input(
            "Preferred output format (detailed/summary/both):",
            validator=lambda x: x.lower() in ["detailed", "summary", "both"],
            error_msg="Please enter: detailed, summary, or both"
        ).lower()
        
        return requirements
    
    def _collect_custom_scenarios(self) -> List[Dict[str, Any]]:
        """Collect custom stress scenarios from user."""
        scenarios = []
        
        while True:
            self.ui.display_info(f"\nDefining custom scenario #{len(scenarios) + 1}")
            
            scenario = {}
            scenario["name"] = self.ui.get_user_input("Scenario name:")
            
            # Scenario type
            scenario_type = self.ui.get_user_input(
                "Scenario type (market/credit/operational/combined):",
                validator=lambda x: x.lower() in ["market", "credit", "operational", "combined"],
                error_msg="Please enter: market, credit, operational, or combined"
            )
            scenario["type"] = scenario_type.lower()
            
            # Severity
            severity = self.ui.get_user_input(
                "Severity level (mild/moderate/severe):",
                validator=lambda x: x.lower() in ["mild", "moderate", "severe"],
                error_msg="Please enter: mild, moderate, or severe"
            )
            scenario["severity"] = severity.lower()
            
            # Duration
            duration = self.ui.get_user_input(
                "Duration (immediate/1_month/3_months/1_year/2_years):",
                validator=lambda x: x in ["immediate", "1_month", "3_months", "1_year", "2_years"],
                error_msg="Please enter: immediate, 1_month, 3_months, 1_year, or 2_years"
            )
            scenario["duration"] = duration
            
            scenarios.append(scenario)
            
            if not self.ui.confirm_action("Add another custom scenario?"):
                break
        
        return scenarios
    
    def _validate_requirements(self, requirements: Dict[str, Any]) -> Dict[str, Any]:
        """Validate the collected requirements."""
        validation = {
            "is_valid": True,
            "warnings": [],
            "errors": [],
            "recommendations": []
        }
        
        # Validate portfolio value
        portfolio_value = requirements.get("portfolio_value", 0)
        if portfolio_value < 1000000:  # Less than $1M
            validation["warnings"].append(
                f"Portfolio value ${portfolio_value:,} is relatively small for comprehensive stress testing"
            )
        elif portfolio_value > 100000000000:  # Greater than $100B
            validation["warnings"].append(
                f"Portfolio value ${portfolio_value:,} is very large - ensure sufficient computational resources"
            )
        
        # Validate risk tolerance vs portfolio type
        risk_tolerance = requirements.get("risk_tolerance")
        portfolio_type = requirements.get("portfolio_type")
        
        if risk_tolerance == "conservative" and portfolio_type in ["hedge_fund"]:
            validation["warnings"].append(
                "Conservative risk tolerance may not align with hedge fund portfolio type"
            )
        
        # Validate time horizon vs scenarios
        time_horizon = requirements.get("time_horizon", 0)
        if time_horizon < 3:
            validation["recommendations"].append(
                "Consider including immediate shock scenarios for short time horizons"
            )
        elif time_horizon > 10:
            validation["recommendations"].append(
                "Consider long-term structural change scenarios for extended time horizons"
            )
        
        # Validate regulatory framework
        regulatory = requirements.get("regulatory_framework", "none")
        if regulatory != "none" and portfolio_type in ["pension_fund", "bank_portfolio", "insurance_portfolio"]:
            validation["recommendations"].append(
                f"Ensure stress scenarios align with {regulatory} requirements"
            )
        
        return validation
    
    def _generate_llm_scenario_recommendations(self, requirements: Dict[str, Any]) -> Dict[str, Any]:
        """Generate intelligent scenario recommendations based on current market research and portfolio characteristics."""
        portfolio_type = requirements.get("portfolio_type")
        risk_tolerance = requirements.get("risk_tolerance")
        time_horizon = requirements.get("time_horizon", 5)
        portfolio_value = requirements.get("portfolio_value", 0)
        regulatory_framework = requirements.get("regulatory_framework", "none")
        
        # Generate contextual scenario recommendations based on current understanding
        scenarios = {}
        
        # Market crash scenario - tailored to current conditions
        if portfolio_type in ["equity_portfolio", "mixed_portfolio", "hedge_fund", "pension_fund"]:
            scenarios["market_crash"] = {
                "name": "Market Stress Scenario",
                "description": "Based on historical volatility patterns and current market conditions",
                "rationale": self._generate_market_crash_rationale(portfolio_type, risk_tolerance),
                "applicability_score": 0.9 if portfolio_type in ["equity_portfolio", "mixed_portfolio"] else 0.7,
                "complexity": "moderate",
                "estimated_duration": "3-12 months",
                "primary_risks": ["equity_volatility", "correlation_breakdown", "liquidity_constraints"]
            }
        
        # Interest rate scenario - based on current yield environment
        if portfolio_type in ["fixed_income", "bank_portfolio", "insurance_portfolio", "pension_fund"]:
            scenarios["interest_rate_shock"] = {
                "name": "Interest Rate Environment Shift",
                "description": "Reflecting potential monetary policy changes and yield curve dynamics",
                "rationale": self._generate_interest_rate_rationale(portfolio_type, time_horizon),
                "applicability_score": 0.95 if portfolio_type == "fixed_income" else 0.8,
                "complexity": "moderate",
                "estimated_duration": "immediate to 2 years", 
                "primary_risks": ["duration_risk", "convexity_risk", "reinvestment_risk"]
            }
        
        # Credit scenario - considering current credit environment
        if portfolio_type in ["bank_portfolio", "fixed_income", "mixed_portfolio"]:
            scenarios["credit_stress"] = {
                "name": "Credit Environment Deterioration",
                "description": "Reflecting potential credit cycle changes and default risk evolution",
                "rationale": self._generate_credit_rationale(portfolio_type, regulatory_framework),
                "applicability_score": 0.9 if portfolio_type == "bank_portfolio" else 0.7,
                "complexity": "high",
                "estimated_duration": "6 months to 3 years",
                "primary_risks": ["default_risk", "credit_spread_risk", "recovery_rate_risk"]
            }
        
        # Geopolitical/operational risks for all portfolios
        scenarios["geopolitical_operational"] = {
            "name": "Geopolitical and Operational Risk Events",
            "description": "Current global tensions and operational risk landscape",
            "rationale": self._generate_geopolitical_rationale(portfolio_type, portfolio_value),
            "applicability_score": 0.6,
            "complexity": "variable",
            "estimated_duration": "days to years",
            "primary_risks": ["supply_chain_disruption", "cyber_risk", "regulatory_changes"]
        }
        
        # Climate risk - increasingly important
        if time_horizon >= 5:
            scenarios["climate_transition"] = {
                "name": "Climate Transition Risk",
                "description": "Physical and transition risks from climate change",
                "rationale": self._generate_climate_rationale(portfolio_type, time_horizon),
                "applicability_score": 0.7 if time_horizon >= 10 else 0.5,
                "complexity": "high", 
                "estimated_duration": "5+ years",
                "primary_risks": ["stranded_assets", "transition_costs", "physical_risks"]
            }
        
        return {
            "scenarios": scenarios,
            "selection_criteria": self._generate_selection_criteria(requirements),
            "prioritization": self._prioritize_scenarios(scenarios, requirements),
            "research_context": self._provide_research_context(),
            "next_steps": ["Detailed parameter calibration", "Historical backtesting", "Monte Carlo preparation"]
        }
    
    def _generate_market_crash_rationale(self, portfolio_type: str, risk_tolerance: str) -> str:
        """Generate rationale for market crash scenario based on current research."""
        base_rationale = "Market stress scenarios should reflect current volatility regimes and correlation structures. "
        
        if portfolio_type == "equity_portfolio":
            return base_rationale + "Equity-focused portfolios require scenarios capturing sector rotation, factor model breakdowns, and liquidity constraints during market stress."
        elif portfolio_type == "hedge_fund":
            return base_rationale + "Hedge fund strategies need scenarios testing strategy-specific risks including crowded trades, leverage constraints, and alpha decay."
        else:
            return base_rationale + "Mixed portfolios benefit from scenarios testing asset class correlation increases and rebalancing challenges."
    
    def _generate_interest_rate_rationale(self, portfolio_type: str, time_horizon: int) -> str:
        """Generate rationale for interest rate scenarios."""
        base_rationale = "Interest rate scenarios should consider current yield curve positioning and central bank policy trajectories. "
        
        if time_horizon <= 2:
            return base_rationale + "Short horizons focus on immediate rate shock impacts and portfolio repositioning effects."
        elif portfolio_type == "pension_fund":
            return base_rationale + "Pension funds require scenarios testing liability matching and funding ratio impacts over extended periods."
        else:
            return base_rationale + "Duration and convexity effects dominate for fixed income heavy portfolios."
    
    def _generate_credit_rationale(self, portfolio_type: str, regulatory_framework: str) -> str:
        """Generate rationale for credit scenarios."""
        base_rationale = "Credit scenarios should reflect current credit cycle positioning and sector-specific vulnerabilities. "
        
        if regulatory_framework in ["basel_iii", "basel_iv"]:
            return base_rationale + "Regulatory capital frameworks require scenarios aligned with supervisory stress testing methodologies."
        elif portfolio_type == "bank_portfolio":
            return base_rationale + "Banking portfolios need scenarios testing loan loss provisions, capital adequacy, and liquidity coverage."
        else:
            return base_rationale + "Credit spread and migration risks dominate for credit-sensitive fixed income portfolios."
    
    def _generate_geopolitical_rationale(self, portfolio_type: str, portfolio_value: float) -> str:
        """Generate rationale for geopolitical scenarios."""
        base_rationale = "Geopolitical scenarios address supply chain, cyber, and regulatory disruptions affecting global markets. "
        
        if portfolio_value > 1000000000:  # $1B+
            return base_rationale + "Large portfolios face heightened operational and reputational risks requiring comprehensive scenario coverage."
        else:
            return base_rationale + "Focus on market-wide disruptions rather than idiosyncratic operational events."
    
    def _generate_climate_rationale(self, portfolio_type: str, time_horizon: int) -> str:
        """Generate rationale for climate scenarios."""
        base_rationale = "Climate scenarios address transition risks from policy changes and physical risks from climate events. "
        
        if time_horizon >= 10:
            return base_rationale + "Extended horizons require scenarios capturing structural economic shifts and stranded asset risks."
        else:
            return base_rationale + "Near-term focus on transition policy impacts and acute physical events."
    
    def _generate_selection_criteria(self, requirements: Dict[str, Any]) -> List[str]:
        """Generate criteria for scenario selection."""
        criteria = [
            "Portfolio relevance and materiality",
            "Historical precedent and plausibility", 
            "Regulatory requirements and supervisory expectations",
            "Computational feasibility and resource constraints",
            "Scenario diversity and comprehensive risk coverage"
        ]
        
        regulatory = requirements.get("regulatory_framework", "none")
        if regulatory != "none":
            criteria.append(f"Alignment with {regulatory} supervisory scenarios")
        
        return criteria
    
    def _prioritize_scenarios(self, scenarios: Dict[str, Any], requirements: Dict[str, Any]) -> Dict[str, float]:
        """Prioritize scenarios based on portfolio characteristics."""
        priorities = {}
        portfolio_type = requirements.get("portfolio_type")
        
        for scenario_name, scenario in scenarios.items():
            base_priority = scenario.get("applicability_score", 0.5)
            
            # Adjust based on portfolio type and scenario type
            if portfolio_type == "equity_portfolio" and "market" in scenario_name:
                base_priority *= 1.3
            elif portfolio_type == "fixed_income" and "interest_rate" in scenario_name:
                base_priority *= 1.3
            elif portfolio_type == "bank_portfolio" and "credit" in scenario_name:
                base_priority *= 1.2
            
            priorities[scenario_name] = min(base_priority, 1.0)
        
        return priorities
    
    def _provide_research_context(self) -> Dict[str, str]:
        """Provide context on current research and market conditions informing scenario design."""
        return {
            "market_regime": "Current market conditions suggest elevated correlation risks and potential volatility regime shifts",
            "policy_environment": "Central bank policy normalization creates duration and credit spread risks",
            "structural_factors": "Technology disruption, demographic shifts, and climate transition create new risk categories",
            "data_considerations": "High-frequency data and alternative data sources improve scenario calibration accuracy",
            "methodology_advances": "Machine learning and scenario simulation techniques enable more sophisticated stress testing"
        }
    
    def _generate_recommendations(self, requirements: Dict[str, Any], 
                                validation: Dict[str, Any],
                                scenario_recommendations: Dict[str, Any]) -> List[str]:
        """Generate recommendations based on requirements, validation, and LLM scenario analysis."""
        recommendations = []
        
        portfolio_type = requirements.get("portfolio_type")
        risk_tolerance = requirements.get("risk_tolerance")
        time_horizon = requirements.get("time_horizon", 0)
        
        # Portfolio-specific recommendations
        if portfolio_type == "equity_portfolio":
            recommendations.append("Focus on market volatility and correlation breakdown scenarios")
            recommendations.append("Include sector-specific and factor model stress tests")
        elif portfolio_type == "fixed_income":
            recommendations.append("Emphasize yield curve and duration risk scenarios")
            recommendations.append("Include credit spread and convexity stress tests")
        elif portfolio_type == "bank_portfolio":
            recommendations.append("Include comprehensive credit loss and capital adequacy scenarios")
            recommendations.append("Test liquidity coverage and funding stress scenarios")
        elif portfolio_type == "insurance_portfolio":
            recommendations.append("Include asset-liability matching stress scenarios")
            recommendations.append("Test catastrophic event and longevity risk scenarios")
        
        # Risk tolerance recommendations
        if risk_tolerance == "conservative":
            recommendations.append("Use moderate scenario parameters with focus on downside protection")
            recommendations.append("Emphasize capital preservation and drawdown control metrics")
        elif risk_tolerance == "aggressive":
            recommendations.append("Include severe tail risk scenarios and maximum stress conditions")
            recommendations.append("Test portfolio resilience under extreme market conditions")
        
        # Time horizon recommendations
        if time_horizon <= 2:
            recommendations.append("Focus on immediate shock scenarios and short-term volatility")
        elif time_horizon >= 10:
            recommendations.append("Include structural change and long-term transition scenarios")
            recommendations.append("Consider climate and demographic transition risks")
        
        # LLM scenario-based recommendations
        scenario_priorities = scenario_recommendations.get("prioritization", {})
        high_priority_scenarios = [name for name, priority in scenario_priorities.items() if priority > 0.8]
        if high_priority_scenarios:
            recommendations.append(f"Prioritize implementation of high-relevance scenarios: {', '.join(high_priority_scenarios)}")
        
        # Research context recommendations
        research_context = scenario_recommendations.get("research_context", {})
        if research_context:
            recommendations.append("Incorporate current market regime characteristics in scenario calibration")
            recommendations.append("Leverage advanced simulation techniques for improved accuracy")
        
        # Add validation recommendations
        recommendations.extend(validation.get("recommendations", []))
        
        return recommendations
    
    def _build_configuration(self, requirements: Dict[str, Any], 
                           recommendations: List[str],
                           scenario_recommendations: Dict[str, Any]) -> Dict[str, Any]:
        """Build the stress test configuration."""
        config = {
            "portfolio_config": {
                "type": requirements.get("portfolio_type"),
                "value": requirements.get("portfolio_value"),
                "risk_tolerance": requirements.get("risk_tolerance"),
                "time_horizon": requirements.get("time_horizon")
            },
            "stress_test_config": {
                "scenarios": list(scenario_recommendations.get("scenarios", {}).keys()),
                "scenario_details": scenario_recommendations.get("scenarios", {}),
                "prioritization": scenario_recommendations.get("prioritization", {}),
                "selection_criteria": scenario_recommendations.get("selection_criteria", []),
                "regulatory_framework": requirements.get("regulatory_framework", "none"),
                "output_format": requirements.get("output_format", "both"),
                "custom_scenarios": requirements.get("custom_scenarios", []),
                "research_context": scenario_recommendations.get("research_context", {})
            },
            "analysis_config": {
                "include_var": True,
                "include_expected_shortfall": True,
                "confidence_levels": [0.95, 0.99],
                "monte_carlo_simulations": 10000,
                "historical_lookback_years": 10
            }
        }
        
        return config
    
    def _create_summary(self, requirements: Dict[str, Any], 
                       validation: Dict[str, Any]) -> str:
        """Create a summary of the requirements analysis."""
        portfolio_type = requirements.get("portfolio_type", "unknown")
        portfolio_value = requirements.get("portfolio_value", 0)
        risk_tolerance = requirements.get("risk_tolerance", "unknown")
        
        summary = f"""
Requirements analysis completed for {portfolio_type} portfolio valued at ${portfolio_value:,}.
Risk tolerance: {risk_tolerance}. Time horizon: {requirements.get('time_horizon', 'unknown')} years.
Regulatory framework: {requirements.get('regulatory_framework', 'none')}.
Validation: {'Passed' if validation.get('is_valid') else 'Failed'} with {len(validation.get('warnings', []))} warnings.
        """.strip()
        
        return summary
    
    def _extract_key_findings(self, requirements: Dict[str, Any], 
                            validation: Dict[str, Any]) -> List[str]:
        """Extract key findings from the requirements analysis."""
        findings = []
        
        portfolio_value = requirements.get("portfolio_value", 0)
        if portfolio_value >= 1000000000:  # $1B+
            findings.append("Large portfolio size requires comprehensive stress testing approach")
        
        portfolio_type = requirements.get("portfolio_type")
        if portfolio_type in ["bank_portfolio", "insurance_portfolio"]:
            findings.append("Regulated portfolio type requires specific regulatory compliance testing")
        
        custom_scenarios = requirements.get("custom_scenarios", [])
        if custom_scenarios:
            findings.append(f"User defined {len(custom_scenarios)} custom stress scenarios")
        
        if validation.get("warnings"):
            findings.append(f"Analysis identified {len(validation['warnings'])} potential concerns")
        
        regulatory = requirements.get("regulatory_framework", "none")
        if regulatory != "none":
            findings.append(f"Regulatory compliance required for {regulatory}")
        
        return findings


def create_requirements_analyst(user_interaction: UserInteraction) -> RequirementsAnalyst:
    """
    Factory function to create a RequirementsAnalyst instance.
    
    Args:
        user_interaction: UserInteraction instance for CLI handling
        
    Returns:
        RequirementsAnalyst instance
    """
    return RequirementsAnalyst(user_interaction)
